// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	user "github.com/GROUP-1-FASE-3/Backend/features/user"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the RepositoryInterface type
type UserRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: input
func (_m *UserRepository) Create(input user.UserCore) (int, error) {
	ret := _m.Called(input)

	var r0 int
	if rf, ok := ret.Get(0).(func(user.UserCore) int); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(user.UserCore) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: data, id
func (_m *UserRepository) Delete(data user.UserCore, id int) (int, error) {
	ret := _m.Called(data, id)

	var r0 int
	if rf, ok := ret.Get(0).(func(user.UserCore, int) int); ok {
		r0 = rf(data, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(user.UserCore, int) error); ok {
		r1 = rf(data, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *UserRepository) GetByID(id int) (user.UserCore, error) {
	ret := _m.Called(id)

	var r0 user.UserCore
	if rf, ok := ret.Get(0).(func(int) user.UserCore); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(user.UserCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, data
func (_m *UserRepository) Update(id int, data user.UserCore) (int, error) {
	ret := _m.Called(id, data)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, user.UserCore) int); ok {
		r0 = rf(id, data)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, user.UserCore) error); ok {
		r1 = rf(id, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepository(t mockConstructorTestingTNewUserRepository) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
